### PR TITLE
do not register html5-boilerplate if Compass is not defined

### PR DESCRIPTION
**Pull request by kucaahbe**
short 'why':
in production we do not need :assets group but we need html5-boilerplate's helper methods
long 'why': http://kucaahbe.github.com/2011/08/30/html5-boilerplate-and-rails3.1.html

### CODE REVIEW

**Comment by sporkd** [comment]
Thanks kucaahbe,

You might want to check out https://github.com/sporkd/html5-rails.

It's a rewrite to address asset pipeline and decoupling.  Still working on a readme, but this gemfile should get you started...

```
source 'http://rubygems.org'

gem 'rails', '3.1.0'

gem 'haml'
gem 'haml-rails', '>= 0.2'
gem 'html5-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'compass', :git => 'git://github.com/chriseppstein/compass.git', :tag => '0.12.alpha.0'
  gem 'compass-html5'
  gem 'coffee-rails', '~> 3.1.0'
  gem 'sass-rails', '~> 3.1.0'
  gem 'uglifier'
end
```

**Comment by kucaahbe** [comment]
I know about html5-rails, but unfortunately just have no time to rewrite existing project, also had no success with html5-rails yet:(

**Comment by sporkd** [comment]
I hear ya. Switching to asset pipeline on existing projects can be an effort. I'm in that same club too.

**Comment by kucaahbe** [comment]
thanks!

**Pull request merged**
